volumes:
  bank-cards-pgdata:

services:
  bank-cards-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${BANK_CARDS_DB}
      POSTGRES_PASSWORD: ${BANK_CARDS_DB_PASSWORD}
      POSTGRES_USER: ${BANK_CARDS_DB_USER}
    ports: ["${BANK_CARDS_DB_PORT}:5432"]
    volumes: ["bank-cards-pgdata:/var/lib/postgresql/data/"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BANK_CARDS_DB_USER} -d ${BANK_CARDS_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bank-cards-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      bank-cards-db: { condition: service_healthy }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-cards-db:5432/${BANK_CARDS_DB}
      SPRING_DATASOURCE_USERNAME: ${BANK_CARDS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${BANK_CARDS_DB_PASSWORD}
    ports: ["${BANK_CARDS_APP_PORT}:${BANK_CARDS_APP_PORT}"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${BANK_CARDS_APP_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

