server:
  port: 8085

spring:
  application:
    name: bankcards

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

springdoc:
    api-docs:
        path: /api-docs
    packages-to-scan: com.example.bankcards.controller

    swagger-ui:
        path: /swagger-ui.html
        url: /api-docs

jwt:
  secretKey: 9f3c8b2a1d4e7f6a5c8d0e2b9a4f6c7d1e8b3a5f0c9d2e6a7b4f8c1d5e
  access-token-expiration: 900
  refresh-token-expiration: 864000

logging:
  file:
    name: logs/bankcards-app.log
    max-size: 10MB
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"